services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "./bin/dev"
    platform: linux/x86_64
    tty: true
    volumes:
      - .:/rails
    ports:
      - "3100:3000"
